export const cards = [
  {
    id: 1,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 1 - yellow.png"),
    text: "new",
    bgColor: '#EC64A2',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 2,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 2 - yellow.png"),
    text: "new",
    bgColor: '#0499DA',
    head:"Busam Faccabo",
    subHeading: 'Medici',
    badge:'New',
  },
  {
    id: 3,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 3 - yellow.png"),
    text: "new",
    bgColor: '#D76129',
    head:"Busam Faccabo",
    subHeading: 'Medici',
    badge:"New",
  },
  {
    id: 4,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 4 - yellow.png"),
    text: "new",
    bgColor: '#E9B942',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 5,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 5 - yellow.png"),
    text: "new",
    bgColor: '#EC64A2',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 6,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 6 - yellow.png"),
    text: "new",
    bgColor: '#0499DA',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 7,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 1 - yellow.png"),
    text: "new",
    bgColor: '#EC64A2',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 8,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 2 - yellow.png"),
    text: "new",
    bgColor: '#0499DA',
    head:"Busam Faccabo",
    subHeading: 'Medici',
    badge:'New',
  },
  {
    id: 9,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 3 - yellow.png"),
    text: "new",
    bgColor: '#D76129',
    head:"Busam Faccabo",
    subHeading: 'Medici',
    badge:"New",
  },
  {
    id: 10,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 4 - yellow.png"),
    text: "new",
    bgColor: '#E9B942',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 11,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 5 - yellow.png"),
    text: "new",
    bgColor: '#EC64A2',
    head:"Busam Faccabo",
    subHeading: 'Medici',
     badge:'New',
  },
  {
    id: 12,
    image: require("../../assets/images/Images-Maestro/Thumbnail Video 6 - yellow.png"),
    text: "new",
    bgColor: '#0499DA',
    head:"Busam Faccabo",
    subHeading: 'Medici',
    badge:'New',
  },
];
