
export const tabContent1 = {
  "1": [
    {
      
      id: 1,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 2,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 3,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 4,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 5,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 6,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 7,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 8,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
    {
      id: 9,
      Name: " Frédéric Chopin",
      Born: "March 1st 1810",
      Pob: "  Żelazowa Wola, Poland",
      Period: ": Romantic",
      Image: require("../../assets/images/Images-Maestro/New Assets/ComposerCardImage.png"),
    },
  ],
};
